"""empty message

Revision ID: 07626f3544b0
Revises: d6647b09fdc6
Create Date: 2016-01-08 16:44:57.639856

"""

# revision identifiers, used by Alembic.
revision = '07626f3544b0'
down_revision = 'd6647b09fdc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
