"""empty message

Revision ID: d45fc76e7452
Revises: 22b3406a0e7c
Create Date: 2016-01-03 11:28:54.135752

"""

# revision identifiers, used by Alembic.
revision = 'd45fc76e7452'
down_revision = '22b3406a0e7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
